version: "3.7"
services:
  ruby:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    depends_on:
      - redis
    environment:
      - BUNDLE_PATH=/bundle/3.1
      - RACK_ENV=test
      - REDIS_HOST=redis
      - SKIP_JS_SPEC=true
    volumes:
      - ..:/app
      - bundler-data:/bundle

  redis:
    image: redis:7-alpine

volumes:
  bundler-data:
    external:
      name: bundler_data
